seed = 1
parent_dir = "exp\\colosseum\\check"
real_data_path = "data\\colosseum\\"
model_type = "mlp"
num_numerical_features = 26
device = "cuda:0"

[model_params]
num_classes = 3
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    1024,
    512,
    512,
    512,
    512,
    512,
    512,
    1024,
]
dropout = 0.10022066208426875

[diffusion_params]
num_timesteps = 500
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 15000
lr = 9.629202505610024e-05
weight_decay = 2.2848724818229906e-05
batch_size = 2048

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 6500
batch_size = 10000
seed = 0

[eval.type]
eval_model = "tractor"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
